tags_to_scrape = [
        "Story Rich",
        "Choices Matter",
        "Mystery",
        "Multiple Endings",
        "Psychological Horror",
        "Management",
        "Drama",
        "Interactive Fiction",
        "Surreal",
        "Narration",
        "Lore-Rich",
        "Investigation",
        "Psychological",
        "Nonlinear",
        "Abstract",
        "Philosophical",
        "Dark Comedy",
        "Conspiracy",
        "Dynamic Narration",
        "Narrative",
        "God Game",
        "Faith",
        "Well-Written"]